<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Introduction to headliner • headliner</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Introduction to headliner">
<meta property="og:description" content="headliner">
<meta property="og:image" content="/logo.svg">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">headliner</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.0.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/intro.html">Introduction to headliner</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/rjake/headliner/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="intro_files/header-attrs-2.7/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Introduction to headliner</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/rjake/headliner/blob/master/vignettes/intro.Rmd"><code>vignettes/intro.Rmd</code></a></small>
      <div class="hidden name"><code>intro.Rmd</code></div>

    </div>

    
    
The goal of <code>headliner</code> is to help analysts to translate facts to insights. In the comparison below (<a href="https://blog.prototypr.io/dashboard-design-5-things-every-ux-designer-should-know-a85c4558d75">source</a>), both dashboards have the same underlying data but how they present the information to the user is very different.
<div style="text-align:center">
<p><img src="figures/facts_vs_insights.png" width="600/"></p>
</div>
<p>Right now, there isn’t anything out of the box to help users dynamically create phrasing like used in the “insights” version without a bit of coding gymnastics. The many ways you could approach it combined with the steps required to say “if positive, show it like this, if negative show it like that” increase the technical debt this kind of code could add to a project. For this reason, <code>headliner</code> is designed to deliver the building blocks required to create these phrases for plot titles, value boxes in <code>shiny</code> or section headers in a report.</p>
<div id="installation" class="section level2">
<h2 class="hasAnchor">
<a href="#installation" class="anchor"></a>Installation</h2>
<p>You can install the dev version of <code>headliner</code> from <a href="https://github.com/rjake/headliner">github</a> with:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">devtools</span><span class="fu">::</span><span class="fu"><a href="https://devtools.r-lib.org//reference/remote-reexports.html">install_github</a></span><span class="op">(</span><span class="st">"rjake/headliner"</span><span class="op">)</span></code></pre></div>
<div id="installation-1" class="section level3">
<h3 class="hasAnchor">
<a href="#installation-1" class="anchor"></a>Installation</h3>
<p>For these examples, I will use a function called <code><a href="../reference/demo_data.html">demo_data()</a></code> to build a data set based on the current date (this was last run on 05/07/21).</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">headliner</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span>
<span class="fu"><a href="../reference/demo_data.html">demo_data</a></span><span class="op">(</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 10 x 5</span>
<span class="co">#&gt;    group     x     y     z date      </span>
<span class="co">#&gt;    &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;date&gt;    </span>
<span class="co">#&gt;  1 a       101    10     1 2021-05-07</span>
<span class="co">#&gt;  2 a       102    20     0 2021-03-07</span>
<span class="co">#&gt;  3 b       103    30     1 2021-01-07</span>
<span class="co">#&gt;  4 b       104    40     0 2020-11-07</span>
<span class="co">#&gt;  5 c       105    50     1 2020-09-07</span>
<span class="co">#&gt;  6 c       106    60     0 2020-07-07</span>
<span class="co">#&gt;  7 d       107    70     1 2020-05-07</span>
<span class="co">#&gt;  8 d       108    80     0 2020-03-07</span>
<span class="co">#&gt;  9 e       109    90     1 2020-01-07</span>
<span class="co">#&gt; 10 e       110   100     0 2019-11-07</span></code></pre></div>
</div>
<div id="a-simple-headline" class="section level3">
<h3 class="hasAnchor">
<a href="#a-simple-headline" class="anchor"></a>A simple headline</h3>
<p>What we want is to say something like this:</p>
<pre><code>#&gt; We have seen a 5.6% decrease compared to the same time last year (101 vs. 107).</code></pre>
<p>We can look at the data an see that about 12 months ago, x was 107 where as today it is 101. We can give these values to <code><a href="../reference/headline.html">headline()</a></code> and get a simple phrase</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/headline.html">headline</a></span><span class="op">(</span>
  compare <span class="op">=</span> <span class="fl">101</span>, 
  reference <span class="op">=</span> <span class="fl">107</span>
<span class="op">)</span>
<span class="co">#&gt; decrease of 6 (101 vs. 107)</span></code></pre></div>
<p>To see how the sentence was constructed, we can look at the components used under the hood. This <code>return_data = TRUE</code> returns a named list. I will condense with <code><a href="../reference/view_list.html">view_list()</a></code></p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/headline.html">headline</a></span><span class="op">(</span><span class="fl">101</span>, <span class="fl">107</span>, return_data <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="../reference/view_list.html">view_list</a></span><span class="op">(</span><span class="op">)</span>
<span class="co">#&gt;                                          VALUES</span>
<span class="co">#&gt; delta                                         6</span>
<span class="co">#&gt; delta_p                                     5.6</span>
<span class="co">#&gt; article_delta                               a 6</span>
<span class="co">#&gt; article_delta_p                           a 5.6</span>
<span class="co">#&gt; comp_value                                  101</span>
<span class="co">#&gt; ref_value                                   107</span>
<span class="co">#&gt; raw_delta                                    -6</span>
<span class="co">#&gt; raw_delta_p                                -5.6</span>
<span class="co">#&gt; article_raw_delta                          a -6</span>
<span class="co">#&gt; article_raw_delta_p                      a -5.6</span>
<span class="co">#&gt; sign                                         -1</span>
<span class="co">#&gt; orig_values                         101 vs. 107</span>
<span class="co">#&gt; trend                                  decrease</span>
<span class="co">#&gt; headline            decrease of 6 (101 vs. 107)</span></code></pre></div>
</div>
<div id="a-custom-headline" class="section level3">
<h3 class="hasAnchor">
<a href="#a-custom-headline" class="anchor"></a>A custom headline</h3>
<p>We can compose it like this using <code><a href="https://glue.tidyverse.org/reference/glue.html">glue::glue()</a></code> syntax</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/headline.html">headline</a></span><span class="op">(</span>
  compare <span class="op">=</span> <span class="fl">101</span>, 
  reference <span class="op">=</span> <span class="fl">107</span>, 
  headline <span class="op">=</span> <span class="st">"We have seen {article_delta_p}% {trend} compared to the same time last year ({orig_values})."</span>
<span class="op">)</span>
<span class="co">#&gt; We have seen a 5.6% decrease compared to the same time last year (101 vs. 107).</span></code></pre></div>
<p>You might have noticed that there are multiple <code>article_*</code> components available. <code>article_delta</code> is for the difference between the two values (“<strong>a</strong> 6 person loss” vs “<strong>an</strong> 8 person loss”), <code>article_delta_p</code> is for the percentage difference for “<strong>a</strong> 5.6%” vs “<strong>an</strong> 8.6%”. You can also add articles to words using <code><a href="../reference/add_article.html">add_article()</a></code>. For example <code>add_artice("increase")</code> gives us “<strong>an</strong> increase” vs <code>add_artice("decrease")</code> “<strong>a</strong> decrease”.</p>
</div>
<div id="helpers-for-dynamic-calculations" class="section level3">
<h3 class="hasAnchor">
<a href="#helpers-for-dynamic-calculations" class="anchor"></a>Helpers for dynamic calculations</h3>
<p>But let’s see if we can make the calculations more dynamic…</p>
<p>First, we can use a function called <code><a href="../reference/add_date_columns.html">add_date_columns()</a></code> to calculate distances from the current date (or the refence date specified) to the values in the <code>date</code> column . With these new fields we can see that 03/07/21 was 61 days ago (or 9 weeks or 2 months, …) from the current date.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/demo_data.html">demo_data</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="../reference/add_date_columns.html">add_date_columns</a></span><span class="op">(</span>date_col <span class="op">=</span> <span class="va">date</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 10 x 11</span>
<span class="co">#&gt;    group     x     y     z date         day  week month quarter calendar_year</span>
<span class="co">#&gt;    &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;         &lt;dbl&gt;</span>
<span class="co">#&gt;  1 a       101    10     1 2021-05-07     0     0     0       0             0</span>
<span class="co">#&gt;  2 a       102    20     0 2021-03-07   -61    -9    -2      -1             0</span>
<span class="co">#&gt;  3 b       103    30     1 2021-01-07  -120   -17    -4      -1             0</span>
<span class="co">#&gt;  4 b       104    40     0 2020-11-07  -181   -26    -6      -2            -1</span>
<span class="co">#&gt;  5 c       105    50     1 2020-09-07  -242   -34    -8      -3            -1</span>
<span class="co">#&gt;  6 c       106    60     0 2020-07-07  -304   -43   -10      -3            -1</span>
<span class="co">#&gt;  7 d       107    70     1 2020-05-07  -365   -52   -12      -4            -1</span>
<span class="co">#&gt;  8 d       108    80     0 2020-03-07  -426   -61   -14      -5            -1</span>
<span class="co">#&gt;  9 e       109    90     1 2020-01-07  -486   -69   -16      -5            -1</span>
<span class="co">#&gt; 10 e       110   100     0 2019-11-07  -547   -78   -18      -6            -2</span>
<span class="co">#&gt; # ... with 1 more variable: fiscal_year &lt;dbl&gt;</span></code></pre></div>
<p>We can then identify some conditions for our comparison (<code>compare</code>) and our reference group (<code>reference</code>). This step uses the kind of logic you would use in <code><a href="https://dplyr.tidyverse.org/reference/filter.html">dplyr::filter()</a></code> or <code><a href="https://rdrr.io/r/base/subset.html">base::subset()</a></code></p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">yoy</span> <span class="op">&lt;-</span> <span class="co"># year over year</span>
  <span class="fu"><a href="../reference/demo_data.html">demo_data</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="../reference/add_date_columns.html">add_date_columns</a></span><span class="op">(</span><span class="va">date</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="../reference/compare_conditions.html">compare_conditions</a></span><span class="op">(</span>
    compare <span class="op">=</span> <span class="op">(</span><span class="va">month</span> <span class="op">==</span> <span class="fl">0</span><span class="op">)</span>,     <span class="co"># this month</span>
    reference <span class="op">=</span> <span class="op">(</span><span class="va">month</span> <span class="op">==</span> <span class="op">-</span><span class="fl">12</span><span class="op">)</span>, <span class="co"># vs 12 months ago</span>
    cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>,                <span class="co"># the column(s) to aggregate</span>
    calc <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>mean <span class="op">=</span> <span class="va">mean</span><span class="op">)</span>    <span class="co"># the list of functions passed to summarise(across(...))</span>
  <span class="op">)</span>

<span class="va">yoy</span>
<span class="co">#&gt; $mean_x_comp</span>
<span class="co">#&gt; [1] 101</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $mean_x_ref</span>
<span class="co">#&gt; [1] 107</span></code></pre></div>
<p>It might look funny to see <code><a href="https://rdrr.io/r/base/list.html">list(mean = mean)</a></code>. The name (left side) is how it will name the values, the right side is the function to use. If I had used <code>calc = list(avg = mean)</code> The names would have been <code>avg_x_*</code>. Because <code><a href="../reference/compare_conditions.html">compare_conditions()</a></code> uses the mean as the default, I’ll omit it going forward. Now that I have my output as a list (or 1 row data frame), I can pipe it into <code><a href="../reference/headline.html">headline()</a></code> to see the underlying data.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">yoy</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="../reference/headline.html">headline</a></span><span class="op">(</span>
    headline <span class="op">=</span> <span class="st">"We have seen {article_delta_p}% {trend} compared to the same time last year ({orig_values})."</span>
  <span class="op">)</span> 
<span class="co">#&gt; We have seen a 5.6% decrease compared to the same time last year (101 vs. 107).</span></code></pre></div>
<p>If your list/data frame has more than 2 values, you can specify the values you need by calling their names</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">car_stats</span> <span class="op">&lt;-</span>
  <span class="va">mtcars</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="../reference/compare_conditions.html">compare_conditions</a></span><span class="op">(</span>
    compare <span class="op">=</span> <span class="va">cyl</span> <span class="op">==</span> <span class="fl">4</span>,
    reference <span class="op">=</span> <span class="va">cyl</span> <span class="op">&gt;</span> <span class="fl">4</span>,
    cols <span class="op">=</span> <span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">"d"</span><span class="op">)</span>,
    calc <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>avg <span class="op">=</span> <span class="va">mean</span>, min <span class="op">=</span> <span class="va">min</span><span class="op">)</span>
  <span class="op">)</span>

<span class="fu"><a href="../reference/view_list.html">view_list</a></span><span class="op">(</span><span class="va">car_stats</span><span class="op">)</span>
<span class="co">#&gt;                   VALUES</span>
<span class="co">#&gt; avg_disp_comp 105.136364</span>
<span class="co">#&gt; avg_disp_ref  296.504762</span>
<span class="co">#&gt; avg_drat_comp   4.070909</span>
<span class="co">#&gt; avg_drat_ref    3.348095</span>
<span class="co">#&gt; min_disp_comp  71.100000</span>
<span class="co">#&gt; min_disp_ref  145.000000</span>
<span class="co">#&gt; min_drat_comp   3.690000</span>
<span class="co">#&gt; min_drat_ref    2.760000</span>

<span class="fu"><a href="../reference/headline.html">headline</a></span><span class="op">(</span>
  <span class="va">car_stats</span>,
  <span class="va">avg_disp_comp</span>,
  <span class="va">avg_disp_ref</span>,
  <span class="st">"Difference in avg. displacement of {delta}cu.in. ({orig_values})"</span>
<span class="op">)</span>
<span class="co">#&gt; Difference in avg. displacement of 191.4cu.in. (105.1 vs. 296.5)</span>

<span class="fu"><a href="../reference/headline.html">headline</a></span><span class="op">(</span>
  <span class="va">car_stats</span>,
  <span class="va">avg_drat_comp</span>,
  <span class="va">avg_drat_ref</span>,
  <span class="st">"Difference in avg. rear axle ratio of {delta} ({orig_values})"</span>
<span class="op">)</span>
<span class="co">#&gt; Difference in avg. rear axle ratio of 0.7 (4.1 vs. 3.3)</span></code></pre></div>
<p><code><a href="../reference/compare_conditions.html">compare_conditions()</a></code> can also be used to compare categorical criteria.</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/demo_data.html">demo_data</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="../reference/compare_conditions.html">compare_conditions</a></span><span class="op">(</span>
    compare <span class="op">=</span> <span class="va">group</span> <span class="op">==</span> <span class="st">"a"</span>,
    reference <span class="op">=</span> <span class="va">group</span> <span class="op">==</span> <span class="st">"c"</span>,
    cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>
  <span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="../reference/headline.html">headline</a></span><span class="op">(</span>
    headline <span class="op">=</span> <span class="st">"Group A ({comp_value}) is {delta} points {trend} Group C ({ref_value})"</span>,
    trend_phrases <span class="op">=</span> <span class="fu"><a href="../reference/trend_terms.html">trend_terms</a></span><span class="op">(</span>more <span class="op">=</span> <span class="st">"ahead"</span>,  less <span class="op">=</span> <span class="st">"behind"</span><span class="op">)</span>
  <span class="op">)</span>
<span class="co">#&gt; Group A (101.5) is 4 points behind Group C (105.5)</span></code></pre></div>
</div>
<div id="within-a-data-frame" class="section level3">
<h3 class="hasAnchor">
<a href="#within-a-data-frame" class="anchor"></a>Within a data frame</h3>
<p>You can also use <code><a href="../reference/add_headline_column.html">add_headline_column()</a></code> to append a column to your data frame with headlines describing each row. You can reference existing columns in the headline and you can bring back specific talking points using <code>return_cols =</code>. You can use this to find the most interesting phrases.</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>
  med <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">tail</a></span><span class="op">(</span><span class="va">LETTERS</span>, <span class="fl">5</span><span class="op">)</span>,
  lab <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"HDL"</span>, <span class="st">"LDL"</span><span class="op">)</span>, length.out <span class="op">=</span> <span class="fl">5</span><span class="op">)</span>,
  pre <span class="op">=</span> <span class="fl">70</span> <span class="op">+</span> <span class="fl">1</span><span class="op">:</span><span class="fl">5</span>,
  post <span class="op">=</span> <span class="fl">70</span> <span class="op">+</span> <span class="fl">6</span><span class="op">:</span><span class="fl">2</span>
<span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="../reference/add_headline_column.html">add_headline_column</a></span><span class="op">(</span>
    compare <span class="op">=</span> <span class="va">post</span>, 
    reference <span class="op">=</span> <span class="va">pre</span>,
    headline <span class="op">=</span> <span class="st">"Using Brand {med}, {lab} {trend}d by {delta} mg/dL"</span>,
    return_cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"delta"</span><span class="op">)</span>
  <span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">delta</span><span class="op">)</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 5 x 6</span>
<span class="co">#&gt;   med   lab     pre  post headline                                delta</span>
<span class="co">#&gt;   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;glue&gt;                                  &lt;dbl&gt;</span>
<span class="co">#&gt; 1 V     HDL      71    76 Using Brand V, HDL increased by 5 mg/dL     5</span>
<span class="co">#&gt; 2 W     LDL      72    75 Using Brand W, LDL increased by 3 mg/dL     3</span>
<span class="co">#&gt; 3 Z     HDL      75    72 Using Brand Z, HDL decreased by 3 mg/dL     3</span>
<span class="co">#&gt; 4 X     HDL      73    74 Using Brand X, HDL increased by 1 mg/dL     1</span>
<span class="co">#&gt; 5 Y     LDL      74    73 Using Brand Y, LDL decreased by 1 mg/dL     1</span></code></pre></div>
</div>
<div id="adding-plural-phrasing-multiple-trend-terms" class="section level3">
<h3 class="hasAnchor">
<a href="#adding-plural-phrasing-multiple-trend-terms" class="anchor"></a>Adding plural phrasing &amp; multiple trend terms</h3>
<p>You can add phrases to customize your sentences. <code>plural_phrases()</code> allows you to add new variables to the list of components available. Here I am adding <code>{people}</code> for use in my headline.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/headline.html">headline</a></span><span class="op">(</span>
  compare <span class="op">=</span> <span class="fl">10</span>,
  reference <span class="op">=</span> <span class="fl">8</span>,
  headline <span class="op">=</span> <span class="st">"{delta_p}% {trend} ({delta} {people})"</span>,
  plural_phrases <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>  
    people <span class="op">=</span> <span class="fu"><a href="../reference/plural_phrasing.html">plural_phrasing</a></span><span class="op">(</span>single <span class="op">=</span> <span class="st">"person"</span>, multi <span class="op">=</span> <span class="st">"people"</span><span class="op">)</span>
  <span class="op">)</span>
<span class="op">)</span>
<span class="co">#&gt; 25% increase (2 people)</span></code></pre></div>
<p>You can actually pass multiple <code><a href="../reference/trend_terms.html">trend_terms()</a></code> and <code><a href="../reference/plural_phrasing.html">plural_phrasing()</a></code> options.</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># lists to use</span>
<span class="va">more_less</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>
    an_increase <span class="op">=</span> <span class="fu"><a href="../reference/trend_terms.html">trend_terms</a></span><span class="op">(</span><span class="st">"an increase"</span>, <span class="st">"a decrease"</span><span class="op">)</span>, 
    more <span class="op">=</span> <span class="fu"><a href="../reference/trend_terms.html">trend_terms</a></span><span class="op">(</span>more <span class="op">=</span> <span class="st">"more"</span>, less <span class="op">=</span> <span class="st">"less"</span><span class="op">)</span>
  <span class="op">)</span>

<span class="va">are_people</span> <span class="op">&lt;-</span>
  <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>
    are <span class="op">=</span> <span class="fu"><a href="../reference/plural_phrasing.html">plural_phrasing</a></span><span class="op">(</span>single <span class="op">=</span> <span class="st">"is"</span>, multi <span class="op">=</span> <span class="st">"are"</span><span class="op">)</span>,
    people <span class="op">=</span> <span class="fu"><a href="../reference/plural_phrasing.html">plural_phrasing</a></span><span class="op">(</span>single <span class="op">=</span> <span class="st">"person"</span>, multi <span class="op">=</span> <span class="st">"people"</span><span class="op">)</span>
  <span class="op">)</span>

<span class="co"># notice the difference in these two outputs</span>
<span class="fu"><a href="../reference/headline.html">headline</a></span><span class="op">(</span>
  compare <span class="op">=</span> <span class="fl">25</span>, 
  reference <span class="op">=</span> <span class="fl">23</span>,
  headline <span class="op">=</span> <span class="st">"There {are} {delta} {more} {people} ({an_increase} of {delta_p}%)"</span>,
  trend_phrases <span class="op">=</span> <span class="va">more_less</span>,
  plural_phrases <span class="op">=</span> <span class="va">are_people</span>
<span class="op">)</span>
<span class="co">#&gt; There are 2 more people (an increase of 8.7%)</span>

<span class="fu"><a href="../reference/headline.html">headline</a></span><span class="op">(</span>
  compare <span class="op">=</span> <span class="fl">25</span>, 
  reference <span class="op">=</span> <span class="fl">26</span>,
  headline <span class="op">=</span> <span class="st">"There {are} {delta} {more} {people} ({an_increase} of {delta_p}%)"</span>,
  trend_phrases <span class="op">=</span> <span class="va">more_less</span>,
  plural_phrases <span class="op">=</span> <span class="va">are_people</span>
<span class="op">)</span>
<span class="co">#&gt; There is 1 less person (a decrease of 3.8%)</span></code></pre></div>
</div>
<div id="when-theres-no-change" class="section level3">
<h3 class="hasAnchor">
<a href="#when-theres-no-change" class="anchor"></a>When there’s no change</h3>
<p>You can also adjust the text if the numbers are the same</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/headline.html">headline</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span>
<span class="co">#&gt; There was no difference.</span>

<span class="fu"><a href="../reference/headline.html">headline</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span>, if_match <span class="op">=</span> <span class="st">"There were no additional applicants ({comp_value} total)"</span><span class="op">)</span>
<span class="co">#&gt; There were no additional applicants (3 total)</span></code></pre></div>
</div>
<div id="an-example-with-valuebox" class="section level3">
<h3 class="hasAnchor">
<a href="#an-example-with-valuebox" class="anchor"></a>An example with <code>valueBox()</code>
</h3>
<p>Here’s an example that uses <code>headliner</code> to create a <code>valueBox()</code> in <code>shiny</code> with dynamic colors and text.</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">box_color</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">yoy</span><span class="op">$</span><span class="va">sign</span> <span class="op">==</span> <span class="op">-</span><span class="fl">1</span>, <span class="st">"red"</span>, <span class="st">"blue"</span><span class="op">)</span>

<span class="fu">valueBox</span><span class="op">(</span>
  value <span class="op">=</span> <span class="fu"><a href="../reference/headline.html">headline</a></span><span class="op">(</span><span class="va">yoy</span>, headline <span class="op">=</span> <span class="st">'{delta_p}% {trend}'</span><span class="op">)</span>,
  subtitle <span class="op">=</span> <span class="st">"vs. the same time last year"</span>,
  color <span class="op">=</span> <span class="va">box_color</span>
<span class="op">)</span> </code></pre></div>
<div style="text-align:center">
<p><img src="figures/value_box.png" width="300/"></p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Jake Riley.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
